Pre commit now runs . Linter, Jest, Lighthouse and will exit if any of those tests break or don't achieve the passing results

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,15 +1,15 @@
 #!/bin/sh
 
 npm run lint
-if test $? = 0
-then printf "\n\n\n ----------------- Remember to fix any existing warnings ----------------- \n\n\n\n"
-elif test $? = 1
-printf "\n\n\n ----------------- Fix all the linting errors before commiting ----------------- \n\n\n\n"
-then exit 0
+if [ $? = 0 ]; then
+    printf "\n\n\n ----------------- Remember to fix any existing warnings ----------------- \n\n\n\n"
+    elif [ $? = 1 ]; then
+    printf "\n\n\n ----------------- Fix all the linting errors before commiting ----------------- \n\n\n\n"
+    exit 0
 fi
 
 npm run test:pc
-if test $? = 1
-then exit 1
+if [ $? = 1 ]; then
+    exit 1
 fi
 npm run performance
diff --git a/scripts/lighthouse_runner b/scripts/lighthouse_runner
--- a/scripts/lighthouse_runner
+++ b/scripts/lighthouse_runner
@@ -4,8 +4,17 @@ rm ./LighthouseOutput/*
 
 GT=$(git log -1 --pretty=format:'%H')
 
-lighthouse http://localhost:3000 --quiet --chrome-flags="--headless" --output 'json' 'html' --output-path ./LighthouseOutput/$(date +%F+%S)."$GT"
 # lighthouse http://localhost:3000 --view --output 'json' 'html' --output-path ./LighthouseOutput/$(date +%F+%S)."$GT"
+lighthouse http://localhost:3000 --quiet --chrome-flags="--headless" --output 'json' 'html' --output-path ./LighthouseOutput/$(date +%F+%S)."$GT"
+if [ $? -eq 0 ]; then
+    echo "something here" $?
+    printf "\n\n\n ----------------- Lighthouse tests ran successfully ----------------- \n\n\n\n"
+    elif [ $? = 1 ]; then
+    printf "\n\n\n ----------------- Lighthouse tests couldn't run, check if: ----------------- \n\n"
+    printf "\n\n ----------------- 1. The project is running on localhost:3000 ----------------- \n\n"
+    printf "\n\n ----------------- 2. The project is running without compiling errors ----------------- \n\n\n\n"
+    exit 0
+fi
 
 docker exec storefront /bin/bash -c "node reportReader.js"
 
