Successfully added jest

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,6 +1,17 @@
-if npm run pc:test = false
-then 
-exit 1
-else
-npm run performance
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "js$")
+if [[ "$STAGED_FILES" = "" ]]; then
+    exit 0
 fi
+
+PASS=true
+
+jest --bail --findRelatedTests $STAGED_FILES
+if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mJest Tests Passed\033[0m"
+else
+echo "$?"
+    echo "\t\033[41mJest Tests Failed\033[0m"
+    PASS=false
+fi
+
+npm run performance
